influxdb:
    image: tutum/influxdb:0.8.8
    env_file: .env
    volumes:
        - ./config/influxdb.toml:/config/config.toml:ro
    ports:
        - "8083:8083"
        - "8086:8086"
    expose:
        - "8090"
        - "8099"
hhvm:
    image: diegomarangoni/hhvm:fastcgi
    working_dir: /data
    env_file: .env
    volumes:
        - ./public_html/:/data
    links:
        - mysql
nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/sites/:/etc/nginx/sites-available:ro
    - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
    - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    - ./nginx/start.sh:/etc/nginx/start.sh
    - ./nginx/logs/:/logs
    - ./public_html/:/data
    links:
    - hhvm
    command: /etc/nginx/start.sh
mysql:
    image: tutum/mysql:5.6
    env_file: .env
    ports:
        - "3306:3306"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
        - "3000:8080"
    environment:
        PMA_HOST: "mysql"
        PMA_PORT: 3306
    links:
        - mysql:db
