influxdb:
    image: tutum/influxdb:0.9
    container_name: influxdb
    env_file: .env
    volumes:
        - ./config/influxdb.toml:/config/config.toml:ro
    ports:
        - "8083:8083"
        - "8086:8086"
    expose:
        - "8090"
        - "8099"
hhvm:
    image: diegomarangoni/hhvm:fastcgi
    container_name: hhvm
    working_dir: /data
    env_file: .env
    volumes:
        - ./public_html/:/data
    links:
        - mysql:db
nginx:
    image: nginx
    container_name: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites/:/etc/nginx/sites-available:ro
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        - ./nginx/start.sh:/etc/nginx/start.sh
        - ./nginx/logs/:/logs
        - ./public_html/:/data
    links:
        - hhvm
    command: /etc/nginx/start.sh
mysql:
    image: tutum/mysql:5.6
    container_name: mysql
    env_file: .env
    ports:
        - "3306:3306"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    env_file: .env
    ports:
        - "8080:8080"
    links:
        - mysql:db
